name: 'lambda-python-template'
description: 'Greet someone and record the time'
inputs:
  rootDir:  # id of input
    description: 'root dir where your app locates'
    required: true
    default: '.'
#outputs:
  #time: # id of output
    #description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.rootDir }}
